import openpyxl
import pandas as pd
import matplotlib.pyplot as plt

csv = pd.read_excel('5 days Events.xlsx')

years = csv['Year'].tolist()

amd = csv['Ahmedabad'].tolist()
amreli = csv['Amreli'].tolist()
anand = csv['Anand'].tolist()
BK = csv['Banas Kantha'].tolist()
bharuch = csv['Bharuch'].tolist()
bhav = csv['Bhavnagar'].tolist()
dahod = csv['Dahod'].tolist()
gandhi = csv['Gandhinagar'].tolist()
jam = csv['Jamnagar'].tolist()
gir = csv['Junagadh'].tolist()
rann = csv['Kachchh'].tolist()
kheda = csv['Kheda'].tolist()
MH = csv['Mahesana'].tolist()
narmada = csv['Narmada'].tolist()
nav = csv['Navsari'].tolist()
PM = csv['Panch Mahals'].tolist()
patan = csv['Patan'].tolist()
PBR = csv['Porbandar'].tolist()
raj = csv['Rajkot'].tolist()
SK = csv['Sabar Kantha'].tolist()
surat = csv['Surat'].tolist()
sunagar = csv['Surendranagar'].tolist()
dang = csv['The Dangs'].tolist()
baroda = csv['Vadodara'].tolist()
valsad = csv['Valsad'].tolist()

plt.figure(figsize=(19, 6))

plt.plot(years, amd, label='Ahmedabad')
plt.plot(years, amreli, label='Amreli')
plt.plot(years, anand, label='Anand')
plt.plot(years, BK, label='Banas Kantha')
plt.plot(years, bharuch, label='Bharuch')
plt.plot(years, bhav, label='Bhavnagar')
plt.plot(years, dahod, label='Dahod')
plt.plot(years, gandhi, label='Gandhinagar')
plt.plot(years, jam, label='Jamnagar')
plt.plot(years, gir, label='Junagadh')
plt.plot(years, rann, label='Kachchh')
plt.plot(years, kheda, label='Kheda')
plt.plot(years, MH, label='Mahesana')
plt.plot(years, narmada, label='Narmada')
plt.plot(years, nav, label='Navsari')
plt.plot(years, PM, label='Panch Mahals')
plt.plot(years, patan, label='Patan')
plt.plot(years, PBR, label='Porbandar')
plt.plot(years, raj, label='Rajkot')
plt.plot(years, SK, label='Sabar Kantha')
plt.plot(years, surat, label='Surat')
plt.plot(years, sunagar, label='Surendranagar')
plt.plot(years, dang, label='The Dangs')
plt.plot(years, baroda, label='Vadodara')
plt.plot(years, valsad, label='Valsad')

plt.xlabel('Years')
plt.ylabel('Number of Heatwaves')
plt.title('Number of Heatwaves in Gujarat')
plt.grid(True)
plt.xticks(rotation=90)
plt.legend(ncol=3)
